# Generated by Django 5.0.1 on 2024-03-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.CharField(max_length=20),
        ),
    ]
