# Generated by Django 5.0.1 on 2024-03-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.CharField(max_length=100),
        ),
    ]
