# Generated by Django 5.0.1 on 2024-03-24 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_appointment_appoint_fee_appointment_appointed_date_and_more'),
        ('payments', '0005_payment_patient_alter_payment_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='appoint_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='account.appointment'),
        ),
    ]
