# Generated by Django 5.0.1 on 2024-03-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_appoint_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='appoint_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='appointment_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
