# Generated by Django 5.0.1 on 2024-03-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_payment_appoint_id_payment_appointment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='appointment_id',
            new_name='appoint_id',
        ),
    ]
