# Generated by Django 5.0.1 on 2024-03-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_nextofkin_kin_gender_remove_user_dob_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
        migrations.RemoveField(
            model_name='otp',
            name='for_user',
        ),
        migrations.AddField(
            model_name='otp',
            name='for_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
