# Generated by Django 5.0.1 on 2024-03-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_otp_options_remove_otp_for_user_otp_for_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appoint_area',
            field=models.CharField(choices=[('', '----------'), ('Dentistry', 'Dentistry'), ('Pharmacy', 'Pharmacy'), ('Laboratory', 'Laboratory Tests'), ('Covid-Screening', 'Covid-19 Screening'), ('Physiotherapy', 'Physiotherapy'), ('Consultation', 'Consultation'), ('VCT', 'HIV Counselling & Treatment'), ('ENT', 'Ear, Nose, and Throat (ENT)'), ('Reproductive Health', 'Reproductive Health'), ('Flu Treatment', 'Flu Treatment'), ('Mental Health', 'Mental Health'), ('Referral', 'Referral'), ('Other issue', 'Other issue')], max_length=19, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='appointmentroom',
            name='room_type',
            field=models.CharField(choices=[('', '-----'), ('Consultation', 'Consultation'), ('HIV VCT', 'HIV VCT'), ('Examination', 'Examination room'), ('Intensive Care', 'Intensive Care Unit (ICU)'), ('Dental Unit', 'Dental Unit'), ('Admission', 'Admission'), ('Covid-Screening', 'Covid-19 Screening'), ('Physiotherapy', 'Physiotherapy'), ('ENT unit', 'Ear, Nose, and Throat (ENT)'), ('Flu', 'Flu Treatment'), ('Reproductive Health', 'Reproductive Health'), ('Mental Health', 'Mental Health'), ('Other issue', 'Other issue'), ('Referral', 'Referral')], max_length=19, verbose_name='Room Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(choices=[('', '----------'), ('Dentistry', 'Dentistry'), ('Pharmacy', 'Pharmacy'), ('Laboratory', 'Laboratory Tests'), ('Covid-Screening', 'Covid-19 Screening'), ('Physiotherapy', 'Physiotherapy'), ('Consultation', 'Consultation'), ('VCT', 'HIV Counselling & Treatment'), ('ENT', 'Ear, Nose, and Throat (ENT)'), ('Reproductive Health', 'Reproductive Health'), ('Flu Treatment', 'Flu Treatment'), ('Mental Health', 'Mental Health'), ('Referral', 'Referral'), ('Other issue', 'Other issue')], max_length=19),
        ),
    ]
