# Generated by Django 5.0.1 on 2024-03-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_appointment_appoint_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentroom',
            options={'verbose_name': 'Appointment Room', 'verbose_name_plural': 'Appointment Rooms'},
        ),
        migrations.AlterModelOptions(
            name='id',
            options={'verbose_name': 'Patient ID', 'verbose_name_plural': 'Patient IDs'},
        ),
        migrations.AlterModelOptions(
            name='nextofkin',
            options={'verbose_name': 'Next of Kin', 'verbose_name_plural': 'Next of Kins'},
        ),
    ]
