# Generated by Django 5.0.1 on 2024-03-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_appointmentroom_options_alter_id_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appoint_reason',
        ),
    ]
