# Generated by Django 5.0.1 on 2024-03-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_appointment_appoint_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.PositiveIntegerField(default=0)),
                ('pending', models.PositiveIntegerField(default=0)),
                ('scheduled', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('canceled', models.PositiveIntegerField(default=0)),
                ('completed', models.PositiveIntegerField(default=0)),
                ('total_booked', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appoint_area',
            field=models.CharField(choices=[('', '----------'), ('Dentistry', 'Dentistry'), ('Pharmacy', 'Pharmacy'), ('Consultation', 'Consultation'), ('Flu Treatment', 'Flu Treatment'), ('ENT', 'Ear, Nose, and Throat (ENT)'), ('Reproductive Health', 'Reproductive Health'), ('Mental Health', 'Mental Health'), ('Physiotherapy', 'Physiotherapy'), ('Covid-Screening', 'Covid-19 Screening'), ('VCT', 'HIV Counselling & Treatment'), ('Laboratory', 'Laboratory Tests'), ('Referral', 'Referral'), ('Other issue', 'Other issue')], max_length=19, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(choices=[('', '----------'), ('Dentistry', 'Dentistry'), ('Pharmacy', 'Pharmacy'), ('Consultation', 'Consultation'), ('Flu Treatment', 'Flu Treatment'), ('ENT', 'Ear, Nose, and Throat (ENT)'), ('Reproductive Health', 'Reproductive Health'), ('Mental Health', 'Mental Health'), ('Physiotherapy', 'Physiotherapy'), ('Covid-Screening', 'Covid-19 Screening'), ('VCT', 'HIV Counselling & Treatment'), ('Laboratory', 'Laboratory Tests'), ('Referral', 'Referral'), ('Other issue', 'Other issue')], max_length=19),
        ),
    ]
