# Generated by Django 5.0.1 on 2024-03-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_appointmentstats_alter_appointment_appoint_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentstats',
            options={'verbose_name': 'Appointment Stat', 'verbose_name_plural': 'Appointment Stats'},
        ),
        migrations.AddField(
            model_name='user',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
