# Generated by Django 5.0.1 on 2024-03-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_appointmentstats_options_user_last_logout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment',
            field=models.BooleanField(blank=True, choices=[(True, 'Verified'), (False, 'Pending')], default=False, null=True, verbose_name='Payment'),
        ),
    ]
