# Generated by Django 5.0.1 on 2024-03-24 14:16

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='kin_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=13, null=True, region=None),
        ),
    ]
