# Generated by Django 5.0.1 on 2024-03-24 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_nextofkin_kin_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appoint_fee',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Appoint Fee'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointed_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Appointed Date'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointed_day',
            field=models.CharField(choices=[('', '-----'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointed_time',
            field=models.CharField(choices=[('', '-----'), ('8:30', '8:30-8:55am'), ('9:00', '9:00-9:25am'), ('9:30', '9:30-9:55am'), ('10:00', '10:00-10:25am'), ('10:30', '10:30-10:55am'), ('11:00', '11:00-11:25am'), ('11:30', '11:30-11:55am'), ('14:00', '2:00-2:25pm'), ('14:30', '2:30-2:55pm'), ('15:00', '3:00-3:25pm'), ('15:30', '3:30-3:55pm'), ('16:00', '4:00-4:25pm'), ('16:30', '4:30-4:55pm')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pay_now',
            field=models.BooleanField(default=True, verbose_name='Pay Now'),
        ),
        migrations.AlterField(
            model_name='appointmentroom',
            name='room_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Room Number'),
        ),
        migrations.AlterField(
            model_name='appointmentroom',
            name='room_type',
            field=models.CharField(choices=[('', '-----'), ('Consultation', 'Consultation'), ('HIV VCT', 'HIV VCT'), ('Examination', 'Examination room'), ('Pharmacy', 'Pharmacy'), ('Lab Tests', 'Laboratory Tests'), ('Dental Unit', 'Dental Unit'), ('Covid-Screening', 'Covid-19 Screening'), ('Physiotherapy', 'Physiotherapy'), ('ENT unit', 'Ear, Nose, and Throat (ENT)'), ('Flu', 'Flu Treatment'), ('Reproductive Health', 'Reproductive Health'), ('Mental Health', 'Mental Health'), ('Other issue', 'Other issue'), ('Referral', 'Referral')], max_length=19, verbose_name='Room Type'),
        ),
    ]
