# Generated by Django 5.0.1 on 2024-03-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_appointment_appoint_fee_appointment_appointed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Appointed Date'),
        ),
    ]
