# Generated by Django 5.0.1 on 2024-03-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_appointment_appointed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointed_day',
            field=models.CharField(choices=[('', '-----'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointed_time',
            field=models.CharField(choices=[('', '-----'), ('8:30', '8:30-8:55am'), ('9:00', '9:00-9:25am'), ('9:30', '9:30-9:55am'), ('10:00', '10:00-10:25am'), ('10:30', '10:30-10:55am'), ('11:00', '11:00-11:25am'), ('11:30', '11:30-11:55am'), ('14:00', '2:00-2:25pm'), ('14:30', '2:30-2:55pm'), ('15:00', '3:00-3:25pm'), ('15:30', '3:30-3:55pm'), ('16:00', '4:00-4:25pm'), ('16:30', '4:30-4:55pm')], max_length=5),
        ),
    ]
