# Generated by Django 5.0.1 on 2024-03-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_appointment_appointed_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointed_date',
            field=models.DateField(blank=True, default='2024-03-26', null=True, verbose_name='Appoint Date'),
        ),
    ]
