# Generated by Django 5.0.1 on 2024-03-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_appointment_appointed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Appoint Date'),
        ),
    ]
