# Generated by Django 5.0.1 on 2024-03-24 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_appointment_appointed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='pay_now',
        ),
    ]
