# Generated by Django 5.0.1 on 2024-03-25 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_appointment_pay_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointed_date',
        ),
    ]
