# Generated by Django 5.0.1 on 2024-03-25 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_appointment_appointed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appoint_duration',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointed_day',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointed_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='victim',
            field=models.CharField(choices=[('', '-----'), ('self', 'Self'), ('next_of_kin', 'Next of Kin')], default='Self', max_length=11, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appoint_fee',
            field=models.PositiveSmallIntegerField(blank=True, default=2, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(50)], verbose_name='Appoint Fee'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment',
            field=models.BooleanField(blank=True, choices=[(True, 'Verified'), (False, 'Unconfirmed')], default=False, null=True, verbose_name='Payment'),
        ),
    ]
