# Generated by Django 5.0.1 on 2024-03-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_remove_appointment_appoint_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointed_room',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appoint_fee',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='victim',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment',
            field=models.BooleanField(blank=True, choices=[(True, 'Verified'), (False, 'N/A')], default=False, null=True, verbose_name='Payment'),
        ),
        migrations.DeleteModel(
            name='AppointmentRoom',
        ),
    ]
