# Generated by Django 5.0.1 on 2024-03-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_remove_appointment_appointed_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appoint_status',
            field=models.CharField(choices=[('', '-----'), ('Failed', 'Failed'), ('Scheduled', 'Scheduled'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], max_length=10, verbose_name='Status'),
        ),
    ]
