# Generated by Django 5.0.1 on 2024-03-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_appointment_appoint_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentStats',
        ),
    ]
